<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #696cff;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #696cff;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #777;
        }
        .filters {
            margin-bottom: 20px;
            background: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
        }
        .filters strong {
            margin-right: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
            color: #333;
            font-weight: bold;
            padding: 8px;
            text-align: left;
        }
        td {
            padding: 8px;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on {{ \Carbon\Carbon::now()->format('d M, Y h:i A') }}</p>
    </div>

    <div class="filters">
        <strong>Applied Filters:</strong>
        @if($request->start_date) <span>Start Date: {{ $request->start_date }}</span> | @endif
        @if($request->end_date) <span>End Date: {{ $request->end_date }}</span> | @endif
        @if($request->shift_type) <span>Shift: {{ $request->shift_type }}</span> | @endif
        @if($request->police_station) <span>Police Station: {{ $request->police_station }}</span> | @endif
        @if(!$request->start_date && !$request->end_date && !$request->shift_type && !$request->police_station)
            <span>None</span>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Shift</th>
                <th>Vehicle No</th>
                <th>Person Name</th>
                <th>Employee ID</th>
                <th>Police Station</th>
                <th>Checking Point</th>
                <th>Recorded By</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $row)
            <tr>
                <td>{{ \Carbon\Carbon::parse($row->shift_date)->format('d M, Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($row->checking_time)->format('h:i A') }}</td>
                <td>{{ $row->shift_type }}</td>
                <td>{{ $row->vehicle_no }}</td>
                <td>{{ $row->person_name }}</td>
                <td>{{ $row->employee_id_no ?? '-' }}</td>
                <td>{{ $row->checkingPoint->police_station ?? '-' }}</td>
                <td>{{ $row->checkingPoint->name ?? '-' }}</td>
                <td>{{ $row->user->name ?? '-' }}</td>
            </tr>
            @endforeach
            @if($records->isEmpty())
            <tr>
                <td colspan="9" style="text-align: center; padding: 20px;">No records found for the selected criteria.</td>
            </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        Report Generated by DriveCheck HRMS System
    </div>

</body>
</html>
